package dk.cachet.carp.dsp.portal

import dk.cachet.carp.dsp.portal.api.Severity
import dk.cachet.carp.dsp.portal.api.ValidationReport
import dk.cachet.carp.dsp.portal.run.EngineValidator
import java.io.File
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

/**
 * The four faults, through the engine's validator.
 *
 * These fixtures are deliberately broken copies of the mobgap workflow, one
 * fault each, generated by carp-dsp's `gen_injections.py`.
 *
 * `inj-missing-output` is not in this list on purpose. It renames a consumer's
 * *input id* rather than its `source.outputId`, so the wiring still points at a
 * real output and mobgap's args are positional - the validator does not flag it,
 * and should not. Fix the generator or drop the fixture; do not assert on it.
 */
class InjectionFixtureTest {

    /** Fixture, and the code the run must be rejected with. */
    private val faults = listOf(
        "inj-cycle" to "cycle",
        "inj-missing-env" to "environment",
        "inj-missing-producer" to "producer",
        "inj-type-mismatch" to "type",
    )

    @Test
    fun `the engine path rejects every injected fault`() =
        faults.forEach { (fixture, _) -> assertRejected(fixture) { EngineValidator.validateDefinition(it) } }

    @Test
    fun `a clean workflow passes`() {
        val report = EngineValidator.validateDefinition(yamlOf("mobgap-gait-analysis"))

        assertTrue(
            report.valid,
            "A clean workflow was rejected: " +
                report.findings.filter { it.severity == Severity.ERROR }.joinToString { it.code },
        )
    }

    private fun assertRejected(fixture: String, validate: (String) -> ValidationReport) {
        val report = validate(yamlOf("injections/$fixture"))
        assertEquals(false, report.valid, "$fixture was accepted")
        assertTrue(
            report.findings.any { it.severity == Severity.ERROR },
            "$fixture produced no error finding",
        )
    }

    /**
     * Straight from the checkout.
     *
     * Fixtures are deliberately broken, so they are kept out of the catalogue and
     * out of the jar - `RepoSource` cannot reach them and neither can a bundled
     * build. The portal's own build already requires a sibling carp-dsp, so
     * finding one here is not an extra demand.
     */
    private fun yamlOf(path: String): String {
        val repo = listOfNotNull(
            System.getenv("DSP_REPO"),
            "../carp-dsp",
            "../../carp-dsp",
        ).map { File(it) }.firstOrNull { File(it, WORKFLOWS).isDirectory }
            ?: error("No carp-dsp checkout beside this repo. Set DSP_REPO to one.")

        val file = File(File(repo, WORKFLOWS), "$path.yaml")
        require(file.isFile) { "No fixture at ${file.absolutePath}" }
        return file.readText()
    }

    private companion object {
        const val WORKFLOWS = "carp.dsp.demo/src/jvmMain/resources/workflows"
    }
}
